<?php
//namespace cool_name_for_your_group\hw3\views;

require_once('GenreMultiSelectHelper.php');
require_once('Config.php');
//define(BASE_URL,"http://localhost/Hw3");
class WriteSomethingView extends View
{
	public $helper;
	public $submitteddata;
	public function __construct()
	{
		parent::__construct();
		$this->helper=new GenreMultiSelectHelper($this);
		
		
	}
	public function render($data)
	{?>
		<!Doctype html>
		<html>
    		<head>
        		<title>Five Thousand Characters - Write Something</title>
        		<link rel="stylesheet" type="text/css" href="styles/common.css">
    		</head>
    		<body>
			<h1>
			<a href="index.php?c=LandingController&m=invoke">Five Thousand Characters</a> - Write Something</h1>
			<form method="post" action="index.php?c=WriteController&m=processForm">
				<label for="titleid">Title</label>
				<input type="text" name="titlename" id="titleid" /><br />
				<label for="authorid">Author</label>
				<input type="text" name="authorname" id="authorid" /><br />
				<label for="identifierid">Identifier</label>
				<input type="text" name="identifiername" id="identifierid" /><br />
				<label for="genreid">Genre</label>
				<?php $this->helper->render($data['genre']); ?>
				<label for="textareaid">Your Writing</label>
				<textarea rows="5" cols="5" id="textareaid" name="story"></textarea>
				<input type="reset" value="Reset" name="resetbutton" />
		    		<input type="submit" value="Save" name="savebutton"/>
			</form>
    		</body>
		</html>
	<?php }
}?>


<!--
A form with three text fields, a select tag, and a textarea. 
The first text field should be labeled "Title", the second text field should be labeled "Author", the third text field should be labeled "Identifier", the select tag should be labeled "Genre" and it should allow multiple genre's to be select, and finally the text area should be labeled your writing. 
Beneath all of these items should be two buttons, a Reset and a Save button. The Reset button clears the data of the form. Clicking the Save button should save a story to the appropriate database tables. The form method should be post and the POST-REDIRECT-GET design pattern should be used. 
After saving, the user should still see their story and other info. 
Your controllers should clean any data sent from this form, there should be a fixed maximum length for each of the fields which is specified in your configs/Config.php file, and the maximum length of the textarea data should be 5000 characters. You should display some kind of error generated by the server (not client side) if data size limits were exceeded. 
If a user clicks on Write Something! on the landing page and comes to this view where nothing is filled in, enters an identifier, and clicks Save; your program should try to look up in the database to find a story with that identifier, and if so, show all the fields of that story for editing.-->
